import {StyleSheet} from 'react-native';

export const colors = {
  //Header
  backgroundHeader: '#000000',
  textHeader: '#DFDFDF',

  //Main
  background: '#272930',

  //Buttons
  playButton: '#D34442',
  topButton: '#3B3E53',
  homeButton: '#121212',
  saveButton: '#338A26',

  //Game
  green: '#0CA31C',
  greenBorder: '#338A26',
  red: '#D20D0D',
  redBorder: '#A02525',
  blue: '#2B7AD2',
  blueBorder: '#2663A6',
  yellow: '#D5CF0F',
  yellowBorder: '#BCB71D',
};

export const styles = StyleSheet.create({
  screenContainer: {
    flex: 1,
    justifyContent: 'center',
    backgroundColor: colors.background,
  },
  screenContainerTopTen: {
    flex: 1,
    justifyContent: 'flex-start',
    backgroundColor: colors.background,
  },
  image: {
    flex: 1,
    justifyContent: 'center',
  },

  homeContainer: {
    position: 'absolute',
    alignSelf: 'center',
    elevation: 20,
    backgroundColor: colors.homeButton,
    borderRadius: 0,
    paddingVertical: 15,
    paddingHorizontal: 100,
    width: '100%',
    bottom: 0,
  },
  topTenBackHome: {
    position: 'absolute',
    alignSelf: 'center',
    elevation: 20,
    backgroundColor: colors.homeButton,
    borderRadius: 0,
    paddingVertical: 15,
    paddingHorizontal: 100,
    width: '100%',
    bottom: 0,
  },
  topContainer: {
    position: 'absolute',
    elevation: 20,
    backgroundColor: colors.topButton,
    borderRadius: 0,
    paddingVertical: 15,
    marginHorizontal: 0,
    paddingHorizontal: 12,
    marginTop: 70,
    width: '100%',
    bottom: 55,
  },
  startGameButton: {
    position: 'absolute',
    borderRadius: 0,
    paddingVertical: 15,
    marginHorizontal: 0,
    paddingHorizontal: 12,
    width: '100%',
    bottom: 120,
  },
  playText: {
    fontSize: 30,
    color: '#fff',
    fontWeight: 'bold',
    alignSelf: 'center',
    textTransform: 'uppercase',
  },
  homeText: {
    fontSize: 20,
    color: '#fff',
    fontWeight: 'bold',
    alignSelf: 'center',
    textTransform: 'uppercase',
  },
  topText: {
    fontSize: 20,
    color: '#fff',
    fontWeight: 'bold',
    alignSelf: 'center',
    textTransform: 'uppercase',
  },

  textPlay: {
    fontSize: 25,
    color: '#fff',
    fontWeight: 'bold',
    alignSelf: 'center',
    textTransform: 'uppercase',
  },
  scoreStyle: {
    position: 'absolute',
    borderRadius: 40,
    width: 70,
    height: 70,
    textAlign: 'center',
    backgroundColor: colors.homeButton,
    color: colors.textHeader,
    fontSize: 50,
    marginTop: -35,
  },
  level: {
    position: 'absolute',
    width: '100%',
    textAlign: 'center',
    color: colors.textHeader,
    fontSize: 35,
    zIndex: 1,
    top: 160,
  },
  compliment: {
    position: 'absolute',
    width: '100%',
    textAlign: 'center',
    color: colors.textHeader,
    fontSize: 25,
    zIndex: 1,
    top: 40,
  },
  errorImg: {
    position: 'absolute',
    width: '100%',
    height: 100,
    padding: 200,
    top: -255,
  },
  error: {
    zIndex: 1,
  },
  score: {
    fontSize: 25,
    color: '#fff',
    marginTop: -130,
    textAlign: 'center',
  },
  speedText: {
    position: 'absolute',
    fontSize: 25,
    color: '#fff',
    alignSelf: 'center',
    top: -70,
  },
  SaveContainer: {
    position: 'absolute',
    alignSelf: 'center',
    elevation: 20,
    backgroundColor: colors.saveButton,
    borderRadius: 20,
    paddingVertical: 10,
    marginHorizontal: 10,
    paddingHorizontal: 12,
    bottom: 15,
    width: '50%',
  },
  speedContainer: {
    position: 'absolute',
    alignSelf: 'center',
    borderRadius: 20,
    paddingVertical: 10,
    marginHorizontal: 10,
    paddingHorizontal: 12,
    bottom: '50%',
    width: '50%',
  },
  playContainer: {
    elevation: 20,
    backgroundColor: colors.playButton,
    borderRadius: 20,
    paddingVertical: 10,
    marginHorizontal: 10,
    paddingHorizontal: 12,
    marginBottom: -320,
  },
  logout: {
    elevation: 20,
    position: 'relative',
    borderRadius: 20,
    paddingVertical: 10,
    marginHorizontal: 10,
    paddingHorizontal: 12,
    justifyContent: 'center',
    alignSelf: 'center',
    paddingBottom: 10,
    marginBottom: -125,
  },
  logoutText: {
    fontSize: 20,
    color: '#fff',
    fontWeight: 'bold',
    textTransform: 'uppercase',
  },
  sound: {
    elevation: 20,
    position: 'absolute',
    borderRadius: 20,
    paddingVertical: 10,
    marginHorizontal: 10,
    paddingHorizontal: 12,
    justifyContent: 'center',
    alignSelf: 'center',
    paddingBottom: 10,
    top: 170,
    opacity: 0.5,
  },
});
